//
// BookCarRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "OpenAPIClientAPI.BookCarRequest")
public typealias BookCarRequest = OpenAPIClientAPI.BookCarRequest

extension OpenAPIClientAPI {

public struct BookCarRequest: Codable, JSONEncodable, Hashable {

    public var VIN: String?
    public var currency: Currency?
    public var startTime: Date?
    public var endTime: Date?

    public init(VIN: String? = nil, currency: Currency? = nil, startTime: Date? = nil, endTime: Date? = nil) {
        self.VIN = VIN
        self.currency = currency
        self.startTime = startTime
        self.endTime = endTime
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case VIN
        case currency
        case startTime
        case endTime
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(VIN, forKey: .VIN)
        try container.encodeIfPresent(currency, forKey: .currency)
        try container.encodeIfPresent(startTime, forKey: .startTime)
        try container.encodeIfPresent(endTime, forKey: .endTime)
    }
}

}
