//
// Booking.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "OpenAPIClientAPI.Booking")
public typealias Booking = OpenAPIClientAPI.Booking

extension OpenAPIClientAPI {

public struct Booking: Codable, JSONEncodable, Hashable {

    public var bookingId: String?
    public var userId: String?
    public var VIN: String?
    public var status: String?

    public init(bookingId: String? = nil, userId: String? = nil, VIN: String? = nil, status: String? = nil) {
        self.bookingId = bookingId
        self.userId = userId
        self.VIN = VIN
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case bookingId
        case userId
        case VIN
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(bookingId, forKey: .bookingId)
        try container.encodeIfPresent(userId, forKey: .userId)
        try container.encodeIfPresent(VIN, forKey: .VIN)
        try container.encodeIfPresent(status, forKey: .status)
    }
}

}
