//
// BookingStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "OpenAPIClientAPI.BookingStatus")
public typealias BookingStatus = OpenAPIClientAPI.BookingStatus

extension OpenAPIClientAPI {

public enum BookingStatus: String, Codable, CaseIterable {
    case pending = "pending"
    case confirmed = "confirmed"
    case completed = "completed"
    case canceled = "canceled"
}
}
