//
// Car.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "OpenAPIClientAPI.Car")
public typealias Car = OpenAPIClientAPI.Car

extension OpenAPIClientAPI {

public struct Car: Codable, JSONEncodable, Hashable {

    public var VIN: String?
    public var model: String?
    public var brand: String?
    public var imageURL: String?
    public var pricePerDay: Double?

    public init(VIN: String? = nil, model: String? = nil, brand: String? = nil, imageURL: String? = nil, pricePerDay: Double? = nil) {
        self.VIN = VIN
        self.model = model
        self.brand = brand
        self.imageURL = imageURL
        self.pricePerDay = pricePerDay
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case VIN
        case model
        case brand
        case imageURL
        case pricePerDay
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(VIN, forKey: .VIN)
        try container.encodeIfPresent(model, forKey: .model)
        try container.encodeIfPresent(brand, forKey: .brand)
        try container.encodeIfPresent(imageURL, forKey: .imageURL)
        try container.encodeIfPresent(pricePerDay, forKey: .pricePerDay)
    }
}

}
