//
// CarListInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "OpenAPIClientAPI.CarListInner")
public typealias CarListInner = OpenAPIClientAPI.CarListInner

extension OpenAPIClientAPI {

public struct CarListInner: Codable, JSONEncodable, Hashable {

    public var VIN: String?
    public var model: String?
    public var brand: String?
    public var imageURL: String?
    public var priceOverAll: Double?
    public var pricePerDay: Double?
    public var currency: Currency?

    public init(VIN: String? = nil, model: String? = nil, brand: String? = nil, imageURL: String? = nil, priceOverAll: Double? = nil, pricePerDay: Double? = nil, currency: Currency? = nil) {
        self.VIN = VIN
        self.model = model
        self.brand = brand
        self.imageURL = imageURL
        self.priceOverAll = priceOverAll
        self.pricePerDay = pricePerDay
        self.currency = currency
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case VIN
        case model
        case brand
        case imageURL
        case priceOverAll
        case pricePerDay
        case currency
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(VIN, forKey: .VIN)
        try container.encodeIfPresent(model, forKey: .model)
        try container.encodeIfPresent(brand, forKey: .brand)
        try container.encodeIfPresent(imageURL, forKey: .imageURL)
        try container.encodeIfPresent(priceOverAll, forKey: .priceOverAll)
        try container.encodeIfPresent(pricePerDay, forKey: .pricePerDay)
        try container.encodeIfPresent(currency, forKey: .currency)
    }
}

}
