//
// Currency.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "OpenAPIClientAPI.Currency")
public typealias Currency = OpenAPIClientAPI.Currency

extension OpenAPIClientAPI {

public enum Currency: String, Codable, CaseIterable {
    case usd = "USD"
    case jpy = "JPY"
    case bgn = "BGN"
    case czk = "CZK"
    case dkk = "DKK"
    case gbp = "GBP"
    case huf = "HUF"
    case pln = "PLN"
    case ron = "RON"
    case sek = "SEK"
    case chf = "CHF"
    case isk = "ISK"
    case nok = "NOK"
    case _try = "TRY"
    case aud = "AUD"
    case brl = "BRL"
    case cad = "CAD"
    case cny = "CNY"
    case hkd = "HKD"
    case idr = "IDR"
    case ils = "ILS"
    case inr = "INR"
    case krw = "KRW"
    case mxn = "MXN"
    case myr = "MYR"
    case nzd = "NZD"
    case php = "PHP"
    case sgd = "SGD"
    case thb = "THB"
    case zar = "ZAR"
    case eur = "EUR"
}
}
