//
// TokenResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "OpenAPIClientAPI.TokenResponse")
public typealias TokenResponse = OpenAPIClientAPI.TokenResponse

extension OpenAPIClientAPI {

public struct TokenResponse: Codable, JSONEncodable, Hashable {

    /** The authentication token */
    public var token: String?

    public init(token: String? = nil) {
        self.token = token
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case token
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(token, forKey: .token)
    }
}

}
