//
// UpdateBookingRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "OpenAPIClientAPI.UpdateBookingRequest")
public typealias UpdateBookingRequest = OpenAPIClientAPI.UpdateBookingRequest

extension OpenAPIClientAPI {

public struct UpdateBookingRequest: Codable, JSONEncodable, Hashable {

    public var bookingId: String?
    public var status: String?

    public init(bookingId: String? = nil, status: String? = nil) {
        self.bookingId = bookingId
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case bookingId
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(bookingId, forKey: .bookingId)
        try container.encodeIfPresent(status, forKey: .status)
    }
}

}
