version: '3.9'
name: rental-ms-compose
services:
  postgres-ms:
    image: postgres:17.2-bookworm
    container_name: postgres-ms-rental
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: main
    ports:
      - "5432:5432"
    volumes:
      - rental_ms_postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  converter-ms:
    image: ghcr.io/megamxl/se-project/java-currency-converter:latest
    ports:
     - "8081:8080"
     - "8082:8082"

  userService:
    image: dev-user-service
    container_name: user-service
    build:
      context: ../Rental-Server
      args:
        SERVICE_LOCATION: cmd/userService/main.go
    ports:
      - "8091:8080"
    environment:
      - CONVERTOR_GRPC_URL=converter:8082
      - DB_HOST=postgres
      - DB_NAME=main
      - DB_PASSWORD=admin
      - DB_PORT=5432
      - DB_SSL-MODE=disable
      - DB_USERNAME=admin
      - SEED_USER_SQL=true
      - WEB_HOST=0.0.0.0
      - WEB_PORT=8080
      - SQL_SCHEMA=user_service
    depends_on:
      - postgres-ms
      - converter-ms
      - pulsar-ms

  carService:
    image: dev-car-service
    container_name: car-service
    build:
      context: ../Rental-Server
      args:
        SERVICE_LOCATION: cmd/carsService/main.go
    ports:
      - "8092:8080"
    environment:
      - CONVERTOR_GRPC_URL=converter:8082
      - DB_HOST=postgres
      - DB_NAME=main
      - DB_PASSWORD=admin
      - DB_PORT=5432
      - DB_SSL-MODE=disable
      - DB_USERNAME=admin
      - SEED_USER_SQL=true
      - WEB_HOST=0.0.0.0
      - WEB_PORT=8080
      - SQL_SCHEMA=car_service
      - PULSAR_PRODUCER=true
      - PULSAR_URL=pulsar://pulsar:6650
    depends_on:
      - postgres-ms
      - converter-ms
      - pulsar-ms

  bookingService:
    image: dev-booking-service
    container_name: booking-service
    build:
      context: ../Rental-Server
      args:
        SERVICE_LOCATION: cmd/bookingService/main.go
    ports:
      - "8093:8080"
    environment:
      - CONVERTOR_GRPC_URL=converter:8082
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=main
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
      - DB_SSL-MODE=disable
      - WEB_HOST=0.0.0.0
      - WEB_PORT=8080
      - SQL_SCHEMA=booking-schema
      - PULSAR_LISTENER=true
      - PULSAR_URL=pulsar://pulsar:6650
    depends_on:
      - postgres-ms
      - converter-ms
      - pulsar-ms
    
  pulsar-ms:
    image: apachepulsar/pulsar:4.0.4
    command: bin/pulsar standalone
    ports:
      - "6650:6650"
      - "8080:8080"
    volumes:
      - pulsardata_ms:/pulsar/data
      - pulsarconf_ms:/pulsar/conf
    tty: true
    stdin_open: true

  
volumes:
  rental_ms_postgres_data:
  pulsardata_ms:
  pulsarconf_ms: