version: '3.9'
name: rental-dev-compose
services:
  postgres:
    image: postgres:17.2-bookworm
    container_name: postgres-car-rental
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: main
    ports:
      - "5432:5432"
    volumes:
      - rental_postgres_data:/var/lib/postgresql/data

  converter:
    image: ghcr.io/megamxl/se-project/java-currency-converter:latest
    ports:
     - "8081:8080"
     - "8082:8082"

  rentalServer:
    image: dev-rental
    container_name: rentalServer
    build: ../Rental-Server
    ports:
      - "8098:8080"
    environment:
      - DB_BACKEND=SQL
      - POSTGRES_DNS=host=postgres user=admin password=admin dbname=main port=5432 sslmode=disable search_path=public
      - WEB_HOST=0.0.0.0
      - WEB_PORT=8080
      - CONVERTOR_SOAP_URL=http://converter:8080/ws
      - SEED_MONOLITH=true
    depends_on:
      - postgres
      - converter
  
volumes:
  rental_postgres_data:
