version: '3.9'
name: rental-dev-compose
services:
  postgres:
    image: postgres:17.2-bookworm
    container_name: postgres-car-rental
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: main
    ports:
      - "5432:5432"
    volumes:
      - rental_postgres_data:/var/lib/postgresql/data
volumes:
  rental_postgres_data: