version: '3.9'
name: rental-dev-compose
services:
  postgres:
    image: postgres:17.2-bookworm
    container_name: postgres-car-rental
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: main
    ports:
      - "5432:5432"
    volumes:
      - rental_postgres_data:/var/lib/postgresql/data

  converter:
    image: ghcr.io/megamxl/se-project/java-currency-converter:latest
    ports:
     - "8081:8080"

  rentalServer:
    image: dev-rental
    container_name: rentalServer
    build: ../Rental-Server
    ports:
      - "8098:8080"
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_NAME=main
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
      - DB_SSL-MODE=disable
      - WEB_HOST=0.0.0.0
      - WEB_PORT=8080
      - CONVERTOR_SOAP_URL=http://host.docker.internal:8081/ws
    depends_on:
      - postgres
      - converter
    
  pulsar:
    image: apachepulsar/pulsar:4.0.4
    command: bin/pulsar standalone
    ports:
      - "6650:6650"
      - "8080:8080"
    volumes:
      - pulsardata:/pulsar/data
      - pulsarconf:/pulsar/conf
    tty: true
    stdin_open: true

  
volumes:
  rental_postgres_data:
  pulsardata:
  pulsarconf:
