on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: master
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        working-directory: ./Currency-Converter-Server/currency.converter
        run: mvn clean install --file pom.xml
      - name: Build and Push Image with Jib
        working-directory: ./Currency-Converter-Server/currency.converter
        run: mvn compile  -Djib.to.auth.username=${{ github.actor }} -Djib.to.auth.password=${{ secrets.GITHUB_TOKEN }} jib:build --file pom.xml
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build rentalService
        working-directory: ./Rental-Server
        run: docker build -t ghcr.io/megamxl/se-project/rental:latest .
      - name: Push rentalService
        working-directory: ./Rental-Server
        run: docker push ghcr.io/megamxl/se-project/rental:latest
        
